/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#005426',
        'primary-container': '#1b6e39',
        'on-primary': '#ffffff',
        'on-primary-container': '#9ceeab',
        'primary-fixed': '#a3f5b2',
        'on-primary-fixed': '#00210b',
        secondary: '#8f4e00',
        'secondary-container': '#fea047',
        'on-secondary': '#ffffff',
        'field-ochre': '#C26D1A',
        'harvest-amber': '#F4A228',
        'sprout-green': '#58A359',
        'leaf-green': '#2E8B57',
        'soil-slate': '#1F2937',
        'cream-surface': '#F8FAFC',
        surface: '#F8FAFC',
        'surface-subtle': '#F1F5F9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f5f9',
        'surface-container': '#e2e8f0',
        'surface-container-high': '#cbd5e1',
        'surface-container-highest': '#94a3b8',
        'on-surface': '#000000',
        'on-surface-variant': '#404940',
        'border-soft': '#DDE3DA',
        'status-available': '#1B6E39',
        'status-available-bg': '#EAF5EE',
        'status-booked': '#616E68',
        'status-booked-bg': '#EFEFEF',
        'status-maintenance': '#D9822B',
        'status-maintenance-bg': '#FEF3E7',
        'status-urgent': '#C53030',
        'status-urgent-bg': '#FDE8E8',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        mono: ['"Space Grotesk"', 'monospace'],
        label: ['"Space Grotesk"', 'sans-serif'],
      },
      spacing: {
        'touch-target-min': '48px',
        'margin-desktop': '2rem',
        'margin-mobile': '1rem',
        'unit-xs': '0.5rem',
        'unit-sm': '0.75rem',
        'unit-md': '1rem',
        'unit-lg': '1.5rem',
        'unit-xl': '2rem',
        'unit-2xl': '3rem',
        'unit-3xl': '4rem',
      },
    },
  },
  plugins: [],
};
